# -*- mode: python ; coding: utf-8 -*-
"""
project @ SitBlinkSip Desktop
author  @ github/ishworrsubedii

One PyInstaller spec for all three platforms, so the freeze step can't drift
between them - the platform branches below are only about what each OS's
packaging expects to receive:

  Linux    a single self-contained executable, which build-deb.sh drops into
           /usr/bin.
  Windows  a --onedir tree. --onefile there re-extracts ~400MB of Qt/OpenCV/
           MediaPipe to %TEMP% on *every* launch (slow, and a reliable way to
           get flagged by antivirus heuristics); the Inno Setup installer
           makes the directory an implementation detail anyway.
  macOS    a --onedir tree wrapped in an .app bundle, because a bundle is the
           only way to get an Info.plist - and without NSCameraUsageDescription
           in one, macOS kills the process the moment it touches the webcam.

Build with:  pyinstaller --noconfirm packaging/pyinstaller/sitblinksip-desktop.spec
"""
import re
import sys
from pathlib import Path

from PyInstaller.utils.hooks import collect_all

PROJECT_ROOT = Path(SPECPATH).resolve().parents[1]

IS_WINDOWS = sys.platform == "win32"
IS_MACOS = sys.platform == "darwin"

VERSION = re.search(
    r'__version__\s*=\s*"([^"]+)"',
    (PROJECT_ROOT / "sitblinksip_desktop" / "__init__.py").read_text(),
).group(1)

BUNDLE_ID = "com.github.ishworrsubedii.sitblinksip-desktop"
ICON_DIR = PROJECT_ROOT / "packaging" / "icons"

if IS_WINDOWS:
    APP_NAME = "SitBlinkSipDesktop"
    icon_file = ICON_DIR / "sitblinksip-desktop.ico"
elif IS_MACOS:
    APP_NAME = "SitBlinkSip Desktop"
    icon_file = ICON_DIR / "sitblinksip-desktop.icns"
else:
    APP_NAME = "sitblinksip-desktop"
    icon_file = None

# Generated by scripts/generate_icons.py; a missing icon should degrade to a
# default-icon build rather than failing the release.
icon = str(icon_file) if icon_file and icon_file.exists() else None

# The alert WAVs are package data, which PyInstaller does not pick up by
# following imports - without this the frozen app runs but is silent.
datas = [
    (
        str(PROJECT_ROOT / "sitblinksip_desktop" / "resources"),
        "sitblinksip_desktop/resources",
    ),
]
binaries = []
hiddenimports = []

# These three each hide native libraries and data files (MediaPipe's .tflite
# and .binarypb graphs, OpenCV's shared objects, Qt's plugins) behind dynamic
# loading that PyInstaller's import analysis cannot see.
for package in ("mediapipe", "cv2", "PySide6"):
    pkg_datas, pkg_binaries, pkg_hiddenimports = collect_all(package)
    datas += pkg_datas
    binaries += pkg_binaries
    hiddenimports += pkg_hiddenimports

a = Analysis(
    [str(PROJECT_ROOT / "pyinstaller_entry.py")],
    pathex=[str(PROJECT_ROOT)],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["tkinter", "pytest", "PySide6.QtWebEngineCore"],
    noarchive=False,
)

pyz = PYZ(a.pure)

if IS_WINDOWS or IS_MACOS:
    exe = EXE(
        pyz,
        a.scripts,
        [],
        exclude_binaries=True,
        name=APP_NAME,
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=False,
        console=False,
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
        icon=icon,
    )

    coll = COLLECT(
        exe,
        a.binaries,
        a.datas,
        strip=False,
        upx=False,
        upx_exclude=[],
        name=APP_NAME,
    )

    if IS_MACOS:
        app = BUNDLE(
            coll,
            name=f"{APP_NAME}.app",
            icon=icon,
            bundle_identifier=BUNDLE_ID,
            version=VERSION,
            info_plist={
                "CFBundleName": APP_NAME,
                "CFBundleDisplayName": APP_NAME,
                "CFBundleShortVersionString": VERSION,
                "CFBundleVersion": VERSION,
                # Without this key macOS terminates the process as soon as it
                # opens the camera - the string is what the permission prompt
                # shows the user, so it has to explain the "why".
                "NSCameraUsageDescription": (
                    "SitBlinkSip uses the camera to count your blinks and check "
                    "your posture. Video is analysed on your Mac, is never "
                    "recorded, and never leaves the machine."
                ),
                # Menu-bar app: no Dock icon, no app switcher entry. Matches
                # how it behaves in the tray on the other two platforms.
                "LSUIElement": True,
                "NSHighResolutionCapable": True,
                # Lets the OS keep the app on the integrated GPU, which is
                # the right trade for a low-rate background webcam loop.
                "NSSupportsAutomaticGraphicsSwitching": True,
                "LSMinimumSystemVersion": "11.0",
            },
        )
else:
    exe = EXE(
        pyz,
        a.scripts,
        a.binaries,
        a.datas,
        [],
        name=APP_NAME,
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=False,
        upx_exclude=[],
        runtime_tmpdir=None,
        console=False,
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
        icon=icon,
    )
